#!/usr/bin/env Rscript

# What you hand BARCS, and what it hands back.
#
# The shortest useful introduction to the method. Each example prints its
# input table, then the call, then the output table, so the mapping from an
# experiment to a function call can be read off directly rather than inferred
# from documentation.
#
#   1. Two experimental groups -- the case original CB2 already handles, run
#      both ways so the outputs can be compared side by side.
#   2. A continuous dose. This is the case CB2 cannot express: the answer is a
#      trend per dose step, not a difference between two arms.
#   3. Dose adjusted for batch, and a named contrast for a two-dose-step
#      increase. Shows covariate adjustment and `bb_contrast()` together.
#   4. A whole screen -- five guides per gene -- taken through to gene-level
#      calls with empirical-null guide consistency.
#
# The progression is the argument: each example adds one thing the previous
# design could not express, and none of them changes the shape of the call.
#
#     Rscript examples/barcs_input_output_examples.R
#
# The rendered output is committed as `docs/barcs-input-output-examples.md`,
# so that document can be regenerated by running this script.

section <- function(title) {
  cat("\n", strrep("=", 72), "\n", title, "\n",
      strrep("=", 72), "\n", sep = "")
}

if (file.exists(file.path("CB2", "DESCRIPTION")) &&
    requireNamespace("devtools", quietly = TRUE)) {
  devtools::load_all("CB2", quiet = TRUE)
} else if (!requireNamespace("CB2", quietly = TRUE)) {
  stop("Install CB2, or run this script from the BARCS repository root.")
}
source(file.path("R", "bbreg.R"))

section("Example 1 input: two experimental groups")

two_group <- data.frame(
  sample = paste0(rep(c("A", "B"), each = 4), 1:4),
  group = factor(rep(c("A", "B"), each = 4)),
  count = c(74, 112, 91, 139, 128, 177, 164, 211),
  total = c(52000, 81000, 69000, 97000, 55000, 76000, 72000, 93000)
)
two_group$proportion <- two_group$count / two_group$total
print(two_group, digits = 9, row.names = FALSE)

fit_a <- fit_ab(
  matrix(two_group$count[two_group$group == "A"], nrow = 1),
  matrix(two_group$total[two_group$group == "A"], nrow = 1)
)
fit_b <- fit_ab(
  matrix(two_group$count[two_group$group == "B"], nrow = 1),
  matrix(two_group$total[two_group$group == "B"], nrow = 1)
)
phat <- c(A = fit_a$phat, B = fit_b$phat)
vhat <- c(A = fit_a$vhat, B = fit_b$vhat)
legacy_t <- diff(phat) / sqrt(sum(vhat))
legacy_df <- sum(vhat)^2 /
  (vhat[1]^2 / 3 + vhat[2]^2 / 3)

section("Example 1A output: original CB2")
original_output <- data.frame(
  phat_A = phat[["A"]],
  phat_B = phat[["B"]],
  effect_B_minus_A = diff(phat),
  std_error = sqrt(sum(vhat)),
  t_value = legacy_t,
  df = legacy_df,
  p_value = 2 * pt(-abs(legacy_t), df = legacy_df)
)
print(original_output, digits = 12, row.names = FALSE)

group_fit <- bbreg(
  count = two_group$count,
  total = two_group$total,
  formula = ~ group,
  data = two_group
)

section("Example 1B output: default BARCS logit model")
print(group_fit$coefficient_table, digits = 12)
cat(
  "The groupB effect is in log-odds units, not raw-proportion units.\n"
)

section("Example 2 input: continuous dose")

dose_input <- data.frame(
  sample = sprintf("dose_%02d", 1:10),
  dose = rep(0:4, each = 2),
  total = rep(c(80000, 100000), 5)
)
dose_input$true_probability <- plogis(-7 + 0.35 * dose_input$dose)
dose_input$count <- round(
  dose_input$total * dose_input$true_probability
)
dose_input$observed_proportion <-
  dose_input$count / dose_input$total
print(dose_input, digits = 9, row.names = FALSE)

dose_fit <- bbreg(
  count = dose_input$count,
  total = dose_input$total,
  formula = ~ dose,
  data = dose_input
)

section("Example 2 output: guide-abundance trend per dose step")
print(dose_fit$coefficient_table, digits = 12)
cat(
  "True dose slope: 0.35; fitted dose slope:",
  sprintf("%.9f", coef(dose_fit)[["dose"]]), "\n"
)

section("Example 3 input: dose with batch adjustment")

adjusted_input <- data.frame(
  sample = sprintf("s%02d", 1:12),
  dose = rep(0:5, 2),
  batch = factor(rep(c("A", "B"), each = 6)),
  total = rep(c(80000, 95000, 85000, 105000, 90000, 100000), 2)
)
adjusted_eta <- -7 + 0.3 * adjusted_input$dose +
  0.2 * (adjusted_input$batch == "B")
adjusted_input$count <- round(
  adjusted_input$total * plogis(adjusted_eta)
)
adjusted_input$observed_proportion <-
  adjusted_input$count / adjusted_input$total
print(adjusted_input, digits = 9, row.names = FALSE)

adjusted_fit <- bbreg(
  count = adjusted_input$count,
  total = adjusted_input$total,
  formula = ~ dose + batch,
  data = adjusted_input
)

section("Example 3A output: dose effect adjusted for batch")
print(adjusted_fit$coefficient_table, digits = 12)

section("Example 3B output: effect of a two-dose-step increase")
two_step <- bb_contrast(adjusted_fit, c(dose = 2))
print(two_step, digits = 12)

section("Example 4 input: one screen with five guides per gene")

control_gene <- rep(sprintf("NTC%02d", 1:10), each = 5)
control_effect <- rep(c(-0.08, -0.04, 0, 0.04, 0.08), 10) +
  rep(seq(-0.02, 0.02, length.out = 10), each = 5)
guide_results <- data.frame(
  gene = c(
    control_gene,
    rep(c("null_gene", "signal_gene"), each = 5)
  ),
  estimate = c(
    control_effect,
    c(-0.05, 0.02, 0, 0.03, -0.01),
    c(0.52, 0.61, 0.58, 0.66, 0.55)
  ),
  std_error = 0.10,
  converged = TRUE
)
print(
  guide_results[guide_results$gene %in% c("null_gene", "signal_gene"), ],
  row.names = FALSE
)

guide_consistency <- bb_gene_consistency(
  guide_results,
  control = grepl("^NTC", guide_results$gene)
)
section("Example 4 output: empirical-null guide consistency")
print(
  guide_consistency[
    guide_consistency$gene %in% c("null_gene", "signal_gene"),
    c(
      "gene", "n_guides", "estimate", "std_error", "raw_statistic", "statistic",
      "guide_direction_agreement", "p_value", "fdr"
    )
  ],
  digits = 8,
  row.names = FALSE
)
cat(
  "Null center:", attr(guide_consistency, "null_center"),
  "null scale:", attr(guide_consistency, "null_scale"),
  "control genes:", attr(guide_consistency, "control_genes"), "\n"
)
cat(attr(guide_consistency, "null_assumption"), "\n")

stopifnot(
  abs(coef(dose_fit)[["dose"]] - 0.35) < 0.001,
  abs(coef(adjusted_fit)[["dose"]] - 0.3) < 0.001,
  abs(coef(adjusted_fit)[["batchB"]] - 0.2) < 0.001,
  abs(two_step$estimate - 2 * coef(adjusted_fit)[["dose"]]) < 1e-12,
  guide_consistency$p_value[
    guide_consistency$gene == "signal_gene"
  ] < 1e-20
)
