// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// bb_wls_system_cpp
Rcpp::List bb_wls_system_cpp(const arma::mat& x, const arma::vec& weight, const arma::vec& response);
RcppExport SEXP _BARCS_bb_wls_system_cpp(SEXP xSEXP, SEXP weightSEXP, SEXP responseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type weight(weightSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type response(responseSEXP);
    rcpp_result_gen = Rcpp::wrap(bb_wls_system_cpp(x, weight, response));
    return rcpp_result_gen;
END_RCPP
}
// bb_wls_solve_cpp
Rcpp::List bb_wls_solve_cpp(const arma::mat& x, const arma::vec& weight, const arma::vec& response, const bool covariance);
RcppExport SEXP _BARCS_bb_wls_solve_cpp(SEXP xSEXP, SEXP weightSEXP, SEXP responseSEXP, SEXP covarianceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type weight(weightSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type response(responseSEXP);
    Rcpp::traits::input_parameter< const bool >::type covariance(covarianceSEXP);
    rcpp_result_gen = Rcpp::wrap(bb_wls_solve_cpp(x, weight, response, covariance));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BARCS_bb_wls_system_cpp", (DL_FUNC) &_BARCS_bb_wls_system_cpp, 3},
    {"_BARCS_bb_wls_solve_cpp", (DL_FUNC) &_BARCS_bb_wls_solve_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_BARCS(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
